modLoader="lowcodefml"
loaderVersion="[40,)"
license="MIT"
[[mods]]
    modId="aquaculture_tinkers"
    version="1.0.0"
    displayName="Tinkers' Aquaculture"
    description='''
    Integration between Aquaculture 2 and Tinkers Construct 
    '''
[[dependencies.aquaculture_tinkers]]
    modId="forge"
    mandatory=true
    versionRange="[40.1.40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.aquaculture_tinkers]]
    modId="tconstruct"
    mandatory=true
    versionRange="[3.6.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.aquaculture_tinkers]]
    modId="jsonthings"
    mandatory=true
    versionRange="[0.4.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.aquaculture_tinkers]]
    modId="aquaculture"
    mandatory=true
    versionRange="[2.5.0,)"
    ordering="NONE"
    side="BOTH"